apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: enmasse-config-maps-rbac
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "star-wars-amq-config" ]
    verbs: [ "get", "update", "patch" ]
